apiVersion: v1
kind: Service
metadata:
  name: sip-minio
spec:
  selector:
    app.kubernetes.io/name: sip-minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
