apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sip-api
spec:
  rules:
    - host: api.sip.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sip-backend
                port:
                  number: 80
